#!/bin/sh

# Parameters follows https://github.com/ncbi-nlp/BioSentVec/blob/master/src/train_biowordvec.sh
# `sentences.txt` should be first generated by `SentenceDumper.java`
fasttext skipgram -input sentences.txt -output n2c2-fasttext -dim 200 -t 0.001 -minCount 0 -neg 10 -wordNgrams 6 -ws 20