library(dplyr)
library(tidyr)
library(ggplot2)
library(ggpubr)

old_wd <- getwd()
setwd("R")

collect_data <- function(file) {
  data <- read.delim(file)
  
  # We reorganize data into rows since it was created manually.
  # May not be necessary if generated by a script.
  data <- data %>% gather(key="method", value="value", factor_key=TRUE, -Criterion)
  
  # Set user friendly names.
  levels(data$method) <- gsub("([A-Z]{3,4}).([A-Z]{2,4})", "\\1-\\2", levels(data$method))
  
  return(data)
}

plot_data <- function(data, title) {
  g <- ggplot(data=data, aes(x=Criterion, y=value, fill=method)) +
    geom_bar(stat="identity", position=position_dodge2(reverse=TRUE), color="black", size=0.25) +
    coord_flip() +
    scale_x_discrete(limits = rev(levels(data$Criterion))) +
    scale_y_continuous(breaks=seq(0,1,0.1), limits=c(0,1)) +
    ylab(title) +
    scale_fill_brewer(palette="Set2") +
    theme_linedraw() +
    theme(legend.title=element_blank())
  return(g)
}

f1_data <- collect_data("f1.tsv")
f1_plot <- plot_data(f1_data, "F1")
ggexport(f1_plot, filename="f1.pdf", height=10)

accuracy_data <- collect_data("accuracy.tsv")
accuracy_plot <- plot_data(accuracy_data, "Accuracy")
ggexport(accuracy_plot, filename="accuracy.pdf", height=10)

setwd(old_wd)